pipeline {
    agent any

    environment {
        GITHUB_TOKEN = credentials('Github_Token')
        AZURE_PUBLISH_PROFILE = credentials('Azure_Publish_Profile') 

    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/AbraarMohiuddin/BookWeb.git', credentialsId: 'Github_Token'
            }
        }

        stage('Restore') {
            steps {
                bat 'dotnet restore'
            }
        }

        stage('Build') {
            steps {
                bat 'dotnet build --configuration Debug'
            }
        }

        stage('Publish') {
            steps {
                bat 'dotnet publish --configuration Release --output publish_output'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image with the name "bookstore-test"
                    bat 'docker build -t bookstore-test -f BookStore/Dockerfile .'
                }
            }
        }

        stage('Cleanup Docker Containers') {
            steps {
                script {
                    // Cleanup Docker images after build
                    bat '''
                    docker rmi bookstore-test || exit /b 0
                    '''
                }
            }
        }
    

        stage('Deploy to Azure') {
            when {
                expression {
                    currentBuild.result == null || currentBuild.result == 'SUCCESS'
                }
            }
            steps {
                script {
                    withCredentials([file(credentialsId: 'Azure_Publish_Profile', variable: 'PUBLISH_PROFILE')]) {
                        bat '''
                        az webapp deployment source config-zip \
                        --resource-group defaultresourcegroup-cau \
                        --name BookStore20241010200200 \
                        --src-path publish_output \
                        --publish-profile %PUBLISH_PROFILE%
                        '''
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
            script {
                bat '''
                docker rmi bookstore-test || exit /b 0
                '''
            }
        }
    }
}