pipeline {
    agent any

    environment {
        GITHUB_TOKEN = credentials('Github_Token')
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/AbraarMohiuddin/BookWeb.git', credentialsId: 'Github_Token'
            }
        }

        stage('Restore') {
            steps {
                bat 'dotnet restore'
            }
        }

        stage('Build') {
            steps {
                bat 'dotnet build --configuration Debug'
            }
        }

        stage('Test') {
            steps {
                bat 'dotnet test'
            }
        }

        stage('Publish') {
            steps {
                bat 'dotnet publish --configuration Release'
            }
        }
        stage('Deploy to Azure') {
            steps {
                echo 'Deploying to Azure...'
                bat """
                    az login --service-principal -u ${AZURE_CREDENTIALS_USR} -p ${AZURE_CREDENTIALS_PSW} --tenant <tenant_id>
                    az webapp deploy --resource-group <DefaultResourceGroup-CAU> --name BookHubProd --src-path ./publish
                """
            }
        }
    }
}
